##Default settings
server:
  port: 9080
spring:
  jooq:
    sql-dialect: Postgres
  jackson:
    serialization:
      writeDatesAsTimestamps: false
    defaultPropertyInclusion: nonEmpty

---
##Development settings
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5439/postgres?currentSchema=primrose,extensions
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
logging:
  level:
    org:
      jooq: 
        tools: debug
        Constants: OFF
    primrose: debug
    

---
##Test settings
spring:
  profiles: test

---
##Production settings
spring:
  profiles: prod
